name: CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          yarn
          cd ios && pod install
      - name: Build iOS
        uses: maierj/fastlane-action@v2.2.1
        env:
          TEAM_ID: ${{ secrets.TEAM_ID }}
        subdirectory: 'ios'
        options: '{ "type": "distribution" }'
      - name: Deploy iOS
        uses: maierj/fastlane-action@v2.2.1
        env:
          TEAM_ID: ${{ secrets.TEAM_ID }}
        subdirectory: 'ios'
        options: '{ "type": "distribution" }'
